data:
  config.yaml: |
    clusterID: ${cluster_id}
    server:
      mapRoles:
        # statically map IAM Roles to a ClusterRole
%{ for iam, k8s in role_mappings ~}
      - roleARN: ${iam}
        username: role:{{SessionName}}
        groups:
        - ${k8s}
%{endfor ~}
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    k8s-app: aws-iam-authenticator
  name: aws-iam-authenticator
  namespace: kube-system
